apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata: { name: vault }
spec:
  provider:
    vault:
      server: {{ .Values.vault.address | quote }}
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.k8sAuthPath | quote }}
          role: {{ .Values.vault.roleName | quote }}
