apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: noa-server
  annotations:
    nginx.ingress.kubernetes.io/rate-limit: '100'
    nginx.ingress.kubernetes.io/limit-rps: '10'
spec:
  rules:
    - host: noa-server.production.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: noa-server
                port:
                  number: 3000
