apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: noa-server-prod

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

images:
  - name: noa-server/noa-server
    newTag: v1.0.0
