apiVersion: v1
kind: Service
metadata:
  name: message-queue-api
  namespace: noa-server
  labels:
    app: message-queue-api
spec:
  type: ClusterIP
  selector:
    app: message-queue-api
  ports:
    - name: http
      port: 8081
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: message-queue-api-external
  namespace: noa-server
  labels:
    app: message-queue-api
spec:
  type: LoadBalancer
  selector:
    app: message-queue-api
  ports:
    - name: http
      port: 80
      targetPort: http
