apiVersion: v1
kind: ServiceAccount
metadata: { name: cas-vfsd }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: { name: cas-vfsd }
rules: [ { apiGroups:[""], resources:["pods"], verbs:["get","list"] } ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: { name: cas-vfsd }
subjects: [ { kind: ServiceAccount, name: cas-vfsd, namespace: default } ]
roleRef: { apiGroup: rbac.authorization.k8s.io, kind: ClusterRole, name: cas-vfsd }
