apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "noa-server.fullname" . }}-config
  labels:
    {{- include "noa-server.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
