{{- if .Values.gatekeeperPolicies.enabled }}
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srequiredpodannotation
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredPodAnnotation
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequiredpodannotation
        violation[{"msg": msg}] {
          input.review.kind.kind == "Pod"
          required := {"cosign.sigstore.dev/verified": "true"}
          some k
          required[k] != input.review.object.metadata.annotations[k]
          msg := sprintf("missing or invalid annotation %v", [k])
        }
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredPodAnnotation
metadata:
  name: require-cosign-verified
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
{{- end }}
