apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: noa-server

resources:
  - namespace.yaml

commonLabels:
  app: noa-server
  managed-by: kustomize

images:
  - name: noa-server
    newName: noa-server/noa-server
    newTag: latest
