apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: noa-server-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

images:
  - name: noa-server/noa-server
    newTag: dev
