name: Octelium - tests-e2e
permissions:
  contents: read
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install --yes libssl-dev
      - name: Set up go
        uses: actions/setup-go@0c52d547c9bc32b0c8faf7aabfb35c35306304d30
        with:
          go-version: '${{env.GO_VERSION}}'
      - name: Check out code into the Go module directory
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Run
        run: |
          go version
          which go
          whoami
          make build-e2e
          make install-cli
          ./bin/octelium-e2e
