name: Octelium - release
permissions:
  contents: read
on:
  push:
    tags:
      - 'octelium-v*.*.*'
    paths:
      - 'octelium/**'
      - '.github/workflows/octelium-release.yml'
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./octelium
    strategy:
      matrix:
        arch: [amd64, arm64]
        os: [linux, darwin, windows]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: GitHub vars
        uses: rlespinasse/github-slug-action@cc11e9682d6c9f95b4a4ee7a73c64af4ed5c4628
      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b0c8faf7aabfb35c35306304d30
        with:
          go-version: '${{env.GO_VERSION}}'
        id: go
      - name: Build
        env:
          GOARCH: ${{matrix.arch}}
          GOOS: ${{matrix.os}}
        run: make build-cli
      - name: Tarball
        if: ${{ matrix.os != 'windows' }}
        run: |
          cd bin
          tar -czvf octelium-${{matrix.os}}-${{matrix.arch}}.tar.gz octelium
          tar -czvf octeliumctl-${{matrix.os}}-${{matrix.arch}}.tar.gz octeliumctl
          tar -czvf octops-${{matrix.os}}-${{matrix.arch}}.tar.gz octops
      - name: save artifacts
        if: ${{ matrix.os != 'windows' }}
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72bd
        with:
          name: release-artifact-${{matrix.os}}-${{matrix.arch}}-${{ env.GITHUB_REF_SLUG }}
          path: bin/*.tar.gz
          retention-days: 1
      - name: zip for Windows
        if: ${{ matrix.os == 'windows' }}
        run: |
          curl -L -o wireguard.zip https://download.wireguard.com/wireguard-nt/wireguard-nt-0.10.1.zip
          unzip wireguard.zip
          cp ./wireguard-nt/bin/${{matrix.arch}}/wireguard.dll ./bin

          cd bin
          zip octelium-${{matrix.os}}-${{matrix.arch}}.zip octelium.exe wireguard.dll
          zip octeliumctl-${{matrix.os}}-${{matrix.arch}}.zip octeliumctl.exe
          zip octops-${{matrix.os}}-${{matrix.arch}}.zip octops.exe
      - name: save Windows artifacts
        if: ${{ matrix.os == 'windows' }}
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72bd
        with:
          name: release-artifact-${{matrix.os}}-${{matrix.arch}}-${{ env.GITHUB_REF_SLUG }}
          path: bin/*.zip
          retention-days: 1

  release:
    name: Release
    runs-on: ubuntu-24.04
    needs: build
    permissions:
      contents: write
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: GitHub vars
        uses: rlespinasse/github-slug-action@cc11e9682d6c9f95b4a4ee7a73c64af4ed5c4628
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          # name: release-artifact-${{ env.GITHUB_REF_SLUG }}
          pattern: release-artifact-*
      - name: ls
        run: ls -la
      - name: Release
        uses: softprops/action-gh-release@4a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z
        with:
          files: |
            release-artifact-*/*
