name: Octelium - git-sync
permissions:
  contents: read
on: push
jobs:
  gitlab:
    name: Gitlab
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0

      - name: Sync to GitLab
        uses: keninkujovic/gitlab-sync@2255578444d23f254d08592bb8434084d29474d5
        with:
          gitlab_url: https://gitlab.com/octelium/octelium.git
          username: geoctl
          gitlab_pat: ${{ secrets.GITLAB_PAT }}
